
local t, vk, ini, actor

function getTbl()
	local ini = ini_file("keys.cfg")
	if ini and ini:section_exist("keys") then
		local t = {}
		local res, id, val = ini:r_line("keys", 0, "", "")
		for s in string.gfind(id, "([ %w_\\]+)%p*") do
			table.insert(t, tonumber(s))
		end
		return t
	end
end

function update()
	if t == nil then 
		t = this.getTbl()
		actor = db.actor
	end
	ini = ini_file("buf.txt")
	if ini then
		for i,v in pairs(t) do
			if ini:section_exist(v) then
				if v ~= vk then
					vk = v
					loadstring("keylogger._"..v.."()")()
					--get_console():execute(string.format("Key_pressed:'%d'", v))
					--news_manager.send_tip(db.actor, "%c[255,240,155,25]Key pressed: '"..v.."'", nil, nil, 1000)
					break
				end
			elseif v == vk then
				vk = nil
			end
		end
		ini = nil
	end
end

-----------------------

-- 'J' - антирад
function _74()
	local it = actor:object("antirad")
	if it then
		this.hud_msg("cant_walk", "Used: Antirad")
		actor:eat(it)
	end
end

-- 'K' - еда
function _75()
	local it = actor:object("bread") or actor:object("kolbasa") or actor:object("conserva")
	if it then
		this.hud_msg("cant_walk", "used: "..game.translate_string(system_ini():r_string(it:section(), "inv_name")))
		actor:eat(it)
	end
end

-- 'U' - энергетик
function _85()
	local it = actor:object("energy_drink")
	if it then
		this.hud_msg("cant_walk", "Used: Energy drink")
		actor:eat(it)
	end
end

-- вывод cs сообщени€
function hud_msg(xml, txt)
	local hud = get_hud()
	hud:AddCustomStatic(xml, true)
	local wnd = hud:GetCustomStatic(xml):wnd()
	wnd:SetText(txt)
	wnd:SetTextY(95)
end

-----------------------
-- ”правление временем
-----------------------
local f, k = 0, 1000
local F = system_ini():r_float("alife", "time_factor")
-- 'NUMPAD3'(Num Lock == On) ускорение временм
function _99()
	f = f + k
	level.set_time_factor(f)
	news_manager.send_tip(actor, "%c[0,250,45,45]TIME FACTOR INCREASED "..f, nil, nil, 10000)
end

-- 'NUMPAD2'(Num Lock == On) восстановление стандартной скорости временм
function _98()
	f = 0
	level.set_time_factor(F)
	news_manager.send_tip(actor, "%c[0,-170,-45,-170]TIME FACTOR STANDARD: "..F, nil, nil, 10000)
end

-- 'NUMPAD1'(Num Lock == On) замедление временм
function _97()
	f = f - k
	if f <= 0 then
		this._98()
	else
		level.set_time_factor(f)
		news_manager.send_tip(actor, "%c[0,220,155,25]TIME FACTOR REDUCED "..f, nil, nil, 10000)
	end	
end
